### ISSUE TITLE
Python package management 

### ISSUE THREAD

**Issue by yevgenybulochnik** [pharmorg/OpenFDA#6]
Wanted to create this issue mostly as food for thought. How do you guys feel about using a python package management lib, like [pipenv](https://github.com/pypa/pipenv) or [poetry](https://github.com/python-poetry/poetry). Both libraries are helpful to pin dependency versions and make dependencies easier to manage (install and update).

If these are kinda overkill at this point we may want to create a `requirements.txt` to pin dependency versions. This isnt a huge deal at this point but we may want to consider this. With the current setup when the docker image is built it will install the latest versions of all the python libraries. This may lead to some users having different versions of these libraries as they develop code for this.

**Comment by finish06** [comment]
I am all for using `requirements.txt`.
